version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/magento
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/renew_etc.sh
      timeout: 300
      runas: root
    - location: scripts/link_efs.sh
      timeout: 300
      runas: root
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root
    - location: scripts/fix_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_magento_scripts.sh
      timeout: 300
      runas: root
    - location: scripts/prepare.sh
      timeout: 300
      runas: root
