version: 0.2

phases:
  build:
    commands:
      - composer config --global http-basic.repo.magento.com 5310458a34d580de1700dfe826ff19a1 255059b03eb9d30604d5ef52fca7465d
      - composer install

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - './app/etc/'
  name: source.zip
